import 'package:recyclescan/core/constants/app_colors.dart';
import 'package:recyclescan/core/models/recycling_category.dart';

class RecyclingData {
  RecyclingData._();

  static List<RecyclingCategory> get categories => const [
        RecyclingCategory(
          id: 'plastic',
          name: 'Plastic',
          imageAsset: 'assets/images/cat_plastic.jpg',
          color: AppColors.plasticColor,
          lightColor: AppColors.plasticLight,
          description: 'Recyclable plastics labeled with resin codes 1–7',
          whatGoesIn: [
            'PET bottles (water, soda)',
            'HDPE containers (milk jugs, shampoo)',
            'Plastic bags (at designated drop-offs)',
            'Yogurt containers',
            'Plastic food containers (clean)',
            'Detergent bottles',
          ],
          whatStaysOut: [
            'Styrofoam / polystyrene',
            'Plastic wrap or film',
            'Dirty or greasy plastic',
            'Plastic straws',
            'Multi-layer packaging',
          ],
          preparationTips: [
            'Rinse containers to remove food residue',
            'Remove caps and lids if different material',
            'Flatten bottles to save space',
            'Check the resin code (number inside triangle)',
          ],
          funFact:
              'A recycled plastic bottle saves enough energy to power a 60-watt light bulb for 6 hours!',
          recycleSymbol: '♻️',
        ),
        RecyclingCategory(
          id: 'paper',
          name: 'Paper',
          imageAsset: 'assets/images/cat_paper.jpg',
          color: AppColors.paperColor,
          lightColor: AppColors.paperLight,
          description: 'Paper and cardboard products',
          whatGoesIn: [
            'Newspapers and magazines',
            'Cardboard boxes (flattened)',
            'Office paper',
            'Paper bags',
            'Cereal boxes',
            'Toilet paper tubes',
            'Egg cartons',
          ],
          whatStaysOut: [
            'Greasy pizza boxes',
            'Wax-coated paper',
            'Paper towels and tissues',
            'Laminated paper',
            'Wet or contaminated paper',
            'Receipts (thermal paper)',
          ],
          preparationTips: [
            'Keep paper dry — wet paper cannot be recycled',
            'Flatten all cardboard boxes',
            'Remove plastic tape and labels when possible',
            'Bundle loose paper together',
          ],
          funFact:
              'Recycling one tonne of paper saves 17 trees and 7,000 gallons of water!',
          recycleSymbol: '📄',
        ),
        RecyclingCategory(
          id: 'glass',
          name: 'Glass',
          imageAsset: 'assets/images/cat_glass.jpg',
          color: AppColors.glassColor,
          lightColor: AppColors.glassLight,
          description: 'Glass bottles and jars',
          whatGoesIn: [
            'Glass bottles (green, brown, clear)',
            'Food jars (sauce, jam, pickles)',
            'Wine and beer bottles',
            'Glass food containers',
          ],
          whatStaysOut: [
            'Broken glass (wrap carefully)',
            'Mirrors and window glass',
            'Light bulbs',
            'Drinking glasses and ceramics',
            'Pyrex or heat-resistant glass',
          ],
          preparationTips: [
            'Rinse jars and bottles before recycling',
            'Remove lids and caps',
            'Separate by colour if required locally',
            'Never mix with other materials',
          ],
          funFact:
              'Glass can be recycled indefinitely without any loss in quality or purity!',
          recycleSymbol: '🍾',
        ),
        RecyclingCategory(
          id: 'metal',
          name: 'Metal',
          imageAsset: 'assets/images/cat_metal.jpg',
          color: AppColors.metalColor,
          lightColor: AppColors.metalLight,
          description: 'Aluminium, steel cans and metal items',
          whatGoesIn: [
            'Aluminium cans (soda, beer)',
            'Steel cans (food tins)',
            'Aluminium foil (clean)',
            'Metal lids and caps',
            'Small metal items',
          ],
          whatStaysOut: [
            'Aerosol cans (if not empty)',
            'Paint cans with paint inside',
            'Large appliances (e-waste)',
            'Contaminated metal',
            'Batteries',
          ],
          preparationTips: [
            'Rinse cans to remove food residue',
            'Crush cans to save space',
            'Clean aluminium foil before recycling',
            'Check locally for aerosol disposal rules',
          ],
          funFact:
              'Recycling aluminium uses only 5% of the energy needed to produce new aluminium!',
          recycleSymbol: '🥫',
        ),
        RecyclingCategory(
          id: 'general',
          name: 'General',
          imageAsset: 'assets/images/cat_general.jpg',
          color: AppColors.generalColor,
          lightColor: AppColors.generalLight,
          description: 'Non-recyclable waste for landfill',
          whatGoesIn: [
            'Food-soiled packaging',
            'Nappies and sanitary products',
            'Broken crockery',
            'Used tissues and paper towels',
            'Non-recyclable plastics',
            'Polystyrene containers',
          ],
          whatStaysOut: [
            'Recyclable materials (use correct bin)',
            'Batteries (hazardous waste)',
            'Chemicals and paint',
            'Medical waste',
            'Electronic items',
          ],
          preparationTips: [
            'Always try to recycle before using general waste',
            'Reduce waste by choosing reusable products',
            'Compost food scraps where possible',
            'Check local council guidelines',
          ],
          funFact:
              'The average person generates 4.5 pounds of trash per day. Small changes make a big difference!',
          recycleSymbol: '🗑️',
        ),
        RecyclingCategory(
          id: 'ewaste',
          name: 'E-Waste',
          imageAsset: 'assets/images/cat_ewaste.jpg',
          color: AppColors.eWasteColor,
          lightColor: AppColors.eWasteLight,
          description: 'Electronic devices and batteries',
          whatGoesIn: [
            'Phones and tablets',
            'Computers and laptops',
            'Batteries (all types)',
            'Cables and chargers',
            'Printers and scanners',
            'TVs and monitors',
          ],
          whatStaysOut: [
            'General recycling bins',
            'Regular landfill',
          ],
          preparationTips: [
            'Wipe personal data before recycling',
            'Take to designated e-waste collection points',
            'Check manufacturer take-back programs',
            'Never put batteries in regular bins',
          ],
          funFact:
              'E-waste is the fastest-growing waste stream in the world, but it contains valuable metals like gold and silver!',
          recycleSymbol: '💻',
        ),
        RecyclingCategory(
          id: 'organic',
          name: 'Organic',
          imageAsset: 'assets/images/cat_organic.jpg',
          color: AppColors.organicColor,
          lightColor: AppColors.organicLight,
          description: 'Food and garden organic waste',
          whatGoesIn: [
            'Fruit and vegetable scraps',
            'Coffee grounds and tea bags',
            'Garden clippings',
            'Bread and grains',
            'Eggshells',
            'Leaves and grass',
          ],
          whatStaysOut: [
            'Meat, fish, and dairy (unless home-composting permits)',
            'Diseased plants',
            'Pet waste',
            'Oily or processed foods',
          ],
          preparationTips: [
            'Use a compost bin for food scraps',
            'Layer "green" and "brown" compost materials',
            'Keep organic bin from getting too wet',
            'Check local green bin collection schedule',
          ],
          funFact:
              'Composting food waste can reduce household landfill contributions by up to 30%!',
          recycleSymbol: '🍃',
        ),
      ];

  static Map<String, RecyclingCategory> get categoriesMap {
    return {for (var c in categories) c.id: c};
  }

  // Expanded barcode product database (250+ products)
  static final List<Map<String, dynamic>> productDatabase = [
    // ── Beverages – Plastic (Bottles) ──
    {'barcode': '5000112637939', 'name': 'Coca-Cola 500ml Bottle', 'brand': 'Coca-Cola', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Remove label and cap. Rinse and recycle.'},
    {'barcode': '5000112548167', 'name': 'Sprite 2L Bottle', 'brand': 'Sprite', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle (type 1). Recycle with caps removed.'},
    {'barcode': '3228857000906', 'name': 'Evian Water 1.5L', 'brand': 'Evian', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET #1 bottle. Remove cap. Crush to save bin space.'},
    {'barcode': '5449000131804', 'name': 'Fanta Orange 500ml', 'brand': 'Fanta', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Rinse and recycle.'},
    {'barcode': '5000112658560', 'name': 'Coca-Cola 1.5L Bottle', 'brand': 'Coca-Cola', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Remove cap and label. Recycle.'},
    {'barcode': '0049000028928', 'name': 'Sprite 20oz Bottle', 'brand': 'Sprite', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Recycle curbside.'},
    {'barcode': '0049000006582', 'name': 'Fanta Orange 20oz', 'brand': 'Fanta', 'categoryId': 'plastic', 'imageEmoji': '🧃', 'notes': 'PET #1. Rinse and recycle.'},
    {'barcode': '0012000010484', 'name': 'Pepsi 20oz Bottle', 'brand': 'Pepsi', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Rinse before recycling.'},
    {'barcode': '0012000161155', 'name': 'Mountain Dew 20oz', 'brand': 'Mountain Dew', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Recyclable.'},
    {'barcode': '5000112658843', 'name': 'Dr Pepper 500ml', 'brand': 'Dr Pepper', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Rinse and recycle.'},
    {'barcode': '5449000131422', 'name': 'Dasani Water 500ml', 'brand': 'Dasani', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET #1 bottle. Recycle in plastic bin.'},
    {'barcode': '0078742090429', 'name': 'Aquafina Water 500ml', 'brand': 'Aquafina', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET #1 bottle. Crush to save space. Recycle.'},
    {'barcode': '5000112479432', 'name': 'Ribena Blackcurrant 500ml', 'brand': 'Ribena', 'categoryId': 'plastic', 'imageEmoji': '🍇', 'notes': 'PET bottle. Rinse and recycle.'},
    {'barcode': '5000112543399', 'name': 'Innocent Smoothie 750ml', 'brand': 'Innocent', 'categoryId': 'plastic', 'imageEmoji': '🍓', 'notes': 'PET plastic bottle. Rinse and recycle.'},
    {'barcode': '0025000001015', 'name': 'Tropicana Pure OJ 52oz', 'brand': 'Tropicana', 'categoryId': 'plastic', 'imageEmoji': '🍊', 'notes': 'HDPE plastic bottle. Recyclable.'},
    {'barcode': '5000112630015', 'name': 'Diet Coke 500ml Bottle', 'brand': 'Coca-Cola', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Rinse and place in plastic recycling.'},
    {'barcode': '5000112648720', 'name': 'Coca-Cola Zero 500ml', 'brand': 'Coca-Cola', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Remove cap and recycle.'},
    {'barcode': '5000112548846', 'name': 'Fanta Lemon 500ml Bottle', 'brand': 'Fanta', 'categoryId': 'plastic', 'imageEmoji': '🍋', 'notes': 'PET plastic bottle. Recyclable.'},
    {'barcode': '3057640100405', 'name': 'Volvic Natural Mineral Water 1.5L', 'brand': 'Volvic', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET bottle. Crush and recycle in plastic bin.'},
    {'barcode': '5010658000045', 'name': 'Highland Spring 1.5L Still Water', 'brand': 'Highland Spring', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': '100% recyclable PET bottle. Cap on or separate.'},
    {'barcode': '5000157024619', 'name': 'Buxton Mineral Water 750ml', 'brand': 'Buxton', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET #1 bottle. Recyclable curbside.'},
    {'barcode': '5010472000529', 'name': 'Lucozade Energy Orange 500ml', 'brand': 'Lucozade', 'categoryId': 'plastic', 'imageEmoji': '⚡', 'notes': 'PET bottle. Peel off outer plastic sleeve to recycle.'},
    {'barcode': '5010472000536', 'name': 'Lucozade Sport Orange 500ml', 'brand': 'Lucozade', 'categoryId': 'plastic', 'imageEmoji': '⚡', 'notes': 'PET bottle. Rinse and recycle.'},
    {'barcode': '0012000001093', 'name': 'Pepsi Max 500ml Bottle', 'brand': 'Pepsi', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Rinse and recycle.'},
    {'barcode': '0012000121111', 'name': '7UP 500ml Bottle', 'brand': '7UP', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Recycle in plastic bin.'},
    {'barcode': '0070847811169', 'name': 'Monster Energy Ultra White Can 500ml', 'brand': 'Monster', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Aluminium can. Crush and recycle in metal bin.'},
    {'barcode': '5060335635226', 'name': 'Prime Hydration Blue Raspberry 500ml', 'brand': 'Prime', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET plastic bottle. Rinse and recycle.'},
    {'barcode': '5060335635233', 'name': 'Prime Hydration Ice Pop 500ml', 'brand': 'Prime', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Remove cap and recycle.'},
    {'barcode': '0080022000011', 'name': 'San Pellegrino Sparkling Water 750ml', 'brand': 'San Pellegrino', 'categoryId': 'glass', 'imageEmoji': '🍾', 'notes': 'Glass bottle. Rinse and place in glass recycling.'},
    {'barcode': '0052000122464', 'name': 'Gatorade Cool Blue 20oz', 'brand': 'Gatorade', 'categoryId': 'plastic', 'imageEmoji': '⚡', 'notes': 'PET #1 bottle. Rinse and recycle.'},
    {'barcode': '0052000328651', 'name': 'Gatorade Lemon Lime 20oz', 'brand': 'Gatorade', 'categoryId': 'plastic', 'imageEmoji': '⚡', 'notes': 'PET bottle. Rinse and recycle curbside.'},
    {'barcode': '5000112450005', 'name': 'Oasis Summer Fruits 500ml', 'brand': 'Oasis', 'categoryId': 'plastic', 'imageEmoji': '🧃', 'notes': 'PET plastic bottle. Recyclable.'},

    // ── Beverages – Metal (Cans) ──
    {'barcode': '5449000000996', 'name': 'Coca-Cola Can 330ml', 'brand': 'Coca-Cola', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Crush after use. Recycle in metal bin.'},
    {'barcode': '5449000131798', 'name': 'Fanta Can 330ml', 'brand': 'Fanta', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Rinse and crush. Recycle.'},
    {'barcode': '5000112116304', 'name': 'Sprite Can 330ml', 'brand': 'Sprite', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Crush and recycle.'},
    {'barcode': '0012000001086', 'name': 'Pepsi Can 330ml', 'brand': 'Pepsi', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Crush and recycle in metal bin.'},
    {'barcode': '4056489564546', 'name': 'Red Bull 250ml Can', 'brand': 'Red Bull', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Aluminium can. Recycle in metal bin.'},
    {'barcode': '5060466512755', 'name': 'Monster Energy Can', 'brand': 'Monster', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Aluminium can — highly recyclable. Recycle in metal bin.'},
    {'barcode': '5000113007674', 'name': 'Schweppes Tonic Can', 'brand': 'Schweppes', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel/aluminium can. Rinse and recycle.'},
    {'barcode': '5411188051558', 'name': 'Heineken Beer Can 330ml', 'brand': 'Heineken', 'categoryId': 'metal', 'imageEmoji': '🍺', 'notes': 'Aluminium can. Rinse and recycle.'},
    {'barcode': '5010339344601', 'name': 'Guinness Stout Can', 'brand': 'Guinness', 'categoryId': 'metal', 'imageEmoji': '🍺', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '5000112630022', 'name': 'Diet Coke Can 330ml', 'brand': 'Coca-Cola', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Highly recyclable metal.'},
    {'barcode': '5000112648737', 'name': 'Coca-Cola Zero Can 330ml', 'brand': 'Coca-Cola', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Empty and recycle.'},
    {'barcode': '0012000001284', 'name': 'Pepsi Max Can 330ml', 'brand': 'Pepsi', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Recyclable.'},
    {'barcode': '5000112658850', 'name': 'Dr Pepper Can 330ml', 'brand': 'Dr Pepper', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Place in metal bin.'},
    {'barcode': '5411188111245', 'name': 'Stella Artois Can 440ml', 'brand': 'Stella Artois', 'categoryId': 'metal', 'imageEmoji': '🍺', 'notes': 'Aluminium beer can. Rinse and recycle.'},
    {'barcode': '5010034000309', 'name': 'Carling Lager Can 440ml', 'brand': 'Carling', 'categoryId': 'metal', 'imageEmoji': '🍺', 'notes': 'Aluminium can. Recyclable.'},
    {'barcode': '5010652000126', 'name': 'San Miguel Beer Can 440ml', 'brand': 'San Miguel', 'categoryId': 'metal', 'imageEmoji': '🍺', 'notes': 'Aluminium can. Recycle in metal bin.'},
    {'barcode': '8002270014027', 'name': 'San Pellegrino Lemon Can 330ml', 'brand': 'San Pellegrino', 'categoryId': 'metal', 'imageEmoji': '🍋', 'notes': 'Aluminium can. Foil top and can are both recyclable metal.'},
    {'barcode': '7613034626097', 'name': 'Nespresso Vertuo Pod', 'brand': 'Nespresso', 'categoryId': 'metal', 'imageEmoji': '☕', 'notes': 'Aluminium pod — return to Nespresso drop-off or recycle via official scheme.'},

    // ── Beverages – Glass (Bottles) ──
    {'barcode': '5411188010128', 'name': 'Heineken 330ml Glass Bottle', 'brand': 'Heineken', 'categoryId': 'glass', 'imageEmoji': '🍺', 'notes': 'Glass bottle. Recycle in glass bin.'},
    {'barcode': '5055492000007', 'name': 'Gordon\'s Gin 70cl Glass', 'brand': 'Gordon\'s', 'categoryId': 'glass', 'imageEmoji': '🍸', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '5000267024806', 'name': 'Smirnoff Vodka 70cl', 'brand': 'Smirnoff', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '5010494006422', 'name': 'Jack Daniel\'s 70cl', 'brand': 'Jack Daniel\'s', 'categoryId': 'glass', 'imageEmoji': '🥃', 'notes': 'Glass bottle. Recycle in glass bin.'},
    {'barcode': '3228857002138', 'name': 'Bordeaux Red Wine Bottle', 'brand': 'Generic', 'categoryId': 'glass', 'imageEmoji': '🍷', 'notes': 'Glass bottle. Remove cork/cap and recycle.'},
    {'barcode': '7501064191122', 'name': 'Corona Extra 330ml Glass Bottle', 'brand': 'Corona', 'categoryId': 'glass', 'imageEmoji': '🍺', 'notes': 'Clear glass bottle. Remove lime and metal cap. Recycle.'},
    {'barcode': '8008440010018', 'name': 'Peroni Nastro Azzurro 330ml', 'brand': 'Peroni', 'categoryId': 'glass', 'imageEmoji': '🍺', 'notes': 'Green glass bottle. Rinse and recycle in glass bin.'},
    {'barcode': '5010103001004', 'name': 'Baileys Original Irish Cream 70cl', 'brand': 'Baileys', 'categoryId': 'glass', 'imageEmoji': '🥃', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '5010677000155', 'name': 'Bombay Sapphire Gin 70cl', 'brand': 'Bombay Sapphire', 'categoryId': 'glass', 'imageEmoji': '🍸', 'notes': 'Blue glass bottle. Recyclable in glass bin.'},
    {'barcode': '7312040017034', 'name': 'Absolut Vodka 70cl', 'brand': 'Absolut', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Clear glass bottle. Rinse and place in glass recycling.'},
    {'barcode': '3185370000332', 'name': 'Moët & Chandon Brut Imperial 75cl', 'brand': 'Moët & Chandon', 'categoryId': 'glass', 'imageEmoji': '🍾', 'notes': 'Heavy glass champagne bottle. Remove foil and wire. Recycle.'},

    // ── Food – Metal Cans & Tins ──
    {'barcode': '5010069230823', 'name': 'Heinz Baked Beans 415g', 'brand': 'Heinz', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel food can. Rinse and recycle in metal bin.'},
    {'barcode': '5000118200403', 'name': 'Heinz Cream of Tomato Soup', 'brand': 'Heinz', 'categoryId': 'metal', 'imageEmoji': '🥣', 'notes': 'Steel can. Rinse before placing in metal recycling.'},
    {'barcode': '5010386019082', 'name': 'Baxters Vegetable Soup', 'brand': 'Baxters', 'categoryId': 'metal', 'imageEmoji': '🥣', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '0048001597971', 'name': 'Campbell\'s Tomato Soup', 'brand': 'Campbell\'s', 'categoryId': 'metal', 'imageEmoji': '🥣', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '5010085117714', 'name': 'John West Tuna in Spring Water', 'brand': 'John West', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel tin. Rinse well. Recycle lid separately.'},
    {'barcode': '0085100001012', 'name': 'Dole Pineapple Chunks Can', 'brand': 'Dole', 'categoryId': 'metal', 'imageEmoji': '🍍', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '5000188001086', 'name': 'Princes Corned Beef', 'brand': 'Princes', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel can. Rinse before recycling.'},
    {'barcode': '5010085243612', 'name': 'Princes Sardines in Tomato Sauce', 'brand': 'Princes', 'categoryId': 'metal', 'imageEmoji': '🐟', 'notes': 'Steel tin. Rinse thoroughly. Recycle.'},
    {'barcode': '8005390000028', 'name': 'Cirio Chopped Tomatoes 400g', 'brand': 'Cirio', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel can. Rinse and recycle in metal bin.'},
    {'barcode': '5000157074218', 'name': 'Napolina Chopped Tomatoes 400g', 'brand': 'Napolina', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel food tin. 100% recyclable.'},
    {'barcode': '0029000016008', 'name': 'Green Giant Sweetcorn 198g', 'brand': 'Green Giant', 'categoryId': 'metal', 'imageEmoji': '🌽', 'notes': 'Steel food tin. Rinse and recycle.'},
    {'barcode': '0037600100021', 'name': 'Spam Chopped Pork and Ham 340g', 'brand': 'Spam', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel tin. Wash clean and recycle.'},
    {'barcode': '5000327004640', 'name': 'Cow & Gate Baby Formula Tin', 'brand': 'Cow & Gate', 'categoryId': 'metal', 'imageEmoji': '👶', 'notes': 'Metal tin. Remove plastic scoop/lid. Recycle metal base.'},
    {'barcode': '0044600302784', 'name': 'Reynolds Aluminium Foil 30ft', 'brand': 'Reynolds', 'categoryId': 'metal', 'imageEmoji': '🫙', 'notes': 'Aluminium foil. Scrunch into a ball before recycling.'},

    // ── Condiments, Jars & Oils – Glass ──
    {'barcode': '3017620422003', 'name': 'Nutella 400g Jar', 'brand': 'Ferrero', 'categoryId': 'glass', 'imageEmoji': '🫙', 'notes': 'Glass jar. Rinse thoroughly. Plastic lid to plastic recycling.'},
    {'barcode': '5000386004131', 'name': 'Heinz Tomato Ketchup Glass 342g', 'brand': 'Heinz', 'categoryId': 'glass', 'imageEmoji': '🍅', 'notes': 'Glass bottle. Rinse and remove lid.'},
    {'barcode': '5010477374809', 'name': 'HP Brown Sauce 255g Glass', 'brand': 'HP', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Glass bottle. Rinse before recycling.'},
    {'barcode': '7613035604957', 'name': 'Nescafé Gold Coffee Jar 200g', 'brand': 'Nescafé', 'categoryId': 'glass', 'imageEmoji': '☕', 'notes': 'Glass jar. Remove plastic/metal lid separately.'},
    {'barcode': '5000196400151', 'name': 'Marmite 250g Jar', 'brand': 'Marmite', 'categoryId': 'glass', 'imageEmoji': '🫙', 'notes': 'Glass jar. Rinse thoroughly. Yellow lid recyclable separately.'},
    {'barcode': '5010044002423', 'name': 'Hartley\'s Strawberry Jam Jar', 'brand': 'Hartley\'s', 'categoryId': 'glass', 'imageEmoji': '🍓', 'notes': 'Glass jar. Rinse and recycle. Metal lid to metal bin.'},
    {'barcode': '3045320001570', 'name': 'Bonne Maman Strawberry Conserve 370g', 'brand': 'Bonne Maman', 'categoryId': 'glass', 'imageEmoji': '🍓', 'notes': 'Glass jar with gingham lid. Rinse jar. Metal lid to metal.'},
    {'barcode': '0070200015063', 'name': 'Tabasco Original Sauce 57ml', 'brand': 'Tabasco', 'categoryId': 'glass', 'imageEmoji': '🌶️', 'notes': 'Small glass bottle. Rinse and recycle.'},
    {'barcode': '0041695002498', 'name': 'Heinz Apple Cider Vinegar', 'brand': 'Heinz', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '8001190011214', 'name': 'Bertolli Olive Oil 750ml Glass', 'brand': 'Bertolli', 'categoryId': 'glass', 'imageEmoji': '🫒', 'notes': 'Glass bottle. Wash with warm water. Recycle in glass bin.'},
    {'barcode': '5054379003778', 'name': 'Olive Oil Glass Bottle 500ml', 'brand': 'Generic', 'categoryId': 'glass', 'imageEmoji': '🫒', 'notes': 'Glass bottle. Rinse with warm soapy water. Recycle.'},
    {'barcode': '5000112550496', 'name': 'Levi Roots Reggae Reggae Sauce', 'brand': 'Levi Roots', 'categoryId': 'glass', 'imageEmoji': '🫙', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '8712566053335', 'name': 'Knorr Beef Touch of Taste Glass 200ml', 'brand': 'Knorr', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '5410126006950', 'name': 'Lotus Biscoff Spread 400g Jar', 'brand': 'Lotus', 'categoryId': 'glass', 'imageEmoji': '🫙', 'notes': 'Glass jar. Rinse clean before recycling.'},

    // ── Cereal & Pantry – Paper/Cardboard ──
    {'barcode': '5000112476431', 'name': 'Kellogg\'s Corn Flakes 750g', 'brand': 'Kellogg\'s', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box recyclable. Inner plastic bag — general waste.'},
    {'barcode': '5000168002601', 'name': 'Weetabix 24 Pack Box', 'brand': 'Weetabix', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box recyclable. Inner wrapper — general waste.'},
    {'barcode': '5000112529013', 'name': 'Quaker Rolled Oats 1kg', 'brand': 'Quaker', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard carton. 100% recyclable in paper bin.'},
    {'barcode': '8001120830012', 'name': 'Barilla Penne Rigate 500g', 'brand': 'Barilla', 'categoryId': 'paper', 'imageEmoji': '🍝', 'notes': 'Cardboard box. Flatten and recycle with paper.'},
    {'barcode': '8001120848185', 'name': 'Barilla Spaghetti No.5 500g', 'brand': 'Barilla', 'categoryId': 'paper', 'imageEmoji': '🍝', 'notes': 'Cardboard box. Recyclable in paper bin.'},
    {'barcode': '0016000275522', 'name': 'Cheerios Cereal Box 375g', 'brand': 'General Mills', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box recyclable. Flatten to save space.'},
    {'barcode': '0038000845550', 'name': 'Kellogg\'s Frosted Flakes', 'brand': 'Kellogg\'s', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box. Recyclable.'},
    {'barcode': '5000112476448', 'name': 'Kellogg\'s Crunchy Nut 500g', 'brand': 'Kellogg\'s', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box is recyclable.'},
    {'barcode': '5000112476455', 'name': 'Kellogg\'s Coco Pops 480g', 'brand': 'Kellogg\'s', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box recyclable.'},
    {'barcode': '5000112476462', 'name': 'Kellogg\'s Special K 500g', 'brand': 'Kellogg\'s', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box. Flatten and place in paper bin.'},
    {'barcode': '5000436013225', 'name': 'Birds Eye Fish Fingers 12pk', 'brand': 'Birds Eye', 'categoryId': 'paper', 'imageEmoji': '🐟', 'notes': 'Cardboard box — recycle. Inner bag — general waste.'},
    {'barcode': '5000436001383', 'name': 'Birds Eye Garden Peas 545g', 'brand': 'Birds Eye', 'categoryId': 'paper', 'imageEmoji': '🫛', 'notes': 'Cardboard box — 100% recyclable.'},
    {'barcode': '5010336025116', 'name': 'McCain Oven Chips 900g', 'brand': 'McCain', 'categoryId': 'paper', 'imageEmoji': '🍟', 'notes': 'Cardboard box — recycle.'},
    {'barcode': '5010666576518', 'name': 'PG Tips Tea Bags 80pk Box', 'brand': 'PG Tips', 'categoryId': 'paper', 'imageEmoji': '🍵', 'notes': 'Cardboard box — recycle. Tea bags can be composted.'},
    {'barcode': '5055953901416', 'name': 'Yorkshire Tea 80 Teabags Box', 'brand': 'Yorkshire Tea', 'categoryId': 'paper', 'imageEmoji': '🍵', 'notes': 'Cardboard box — recycle. Tea bags to organic food waste.'},
    {'barcode': '5010338000010', 'name': 'Twinings English Breakfast Tea 50s', 'brand': 'Twinings', 'categoryId': 'paper', 'imageEmoji': '🍵', 'notes': 'Cardboard box. Recyclable.'},
    {'barcode': '5010663213217', 'name': 'Persil Non-Bio Powder 2.6kg', 'brand': 'Persil', 'categoryId': 'paper', 'imageEmoji': '📦', 'notes': 'Cardboard box. Recyclable in paper/card bin.'},
    {'barcode': '4015400438502', 'name': 'Andrex Toilet Tissue Core Tubes', 'brand': 'Andrex', 'categoryId': 'paper', 'imageEmoji': '🧻', 'notes': 'Cardboard inner tubes are 100% recyclable paper.'},
    {'barcode': '5000347012400', 'name': 'Paracetamol 500mg 16 Tablets', 'brand': 'Generic', 'categoryId': 'paper', 'imageEmoji': '💊', 'notes': 'Outer cardboard box recyclable with paper.'},
    {'barcode': '5000347012417', 'name': 'Ibuprofen 400mg 24 Tablets', 'brand': 'Generic', 'categoryId': 'paper', 'imageEmoji': '💊', 'notes': 'Outer cardboard box is recyclable.'},
    {'barcode': '5000158064409', 'name': 'Kleenex Balsam Facial Tissues Box', 'brand': 'Kleenex', 'categoryId': 'paper', 'imageEmoji': '📦', 'notes': 'Cardboard box — recycle. Used tissues — general waste.'},

    // ── Cleaning & Household – Plastic ──
    {'barcode': '5000120102348', 'name': 'Fairy Original Washing Up Liquid 433ml', 'brand': 'Fairy', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'PET bottle. Empty, rinse, and recycle.'},
    {'barcode': '4084500943292', 'name': 'Ariel Washing Liquid 1.3L', 'brand': 'Ariel', 'categoryId': 'plastic', 'imageEmoji': '🧺', 'notes': 'HDPE bottle. Recycle once completely empty.'},
    {'barcode': '8720181099428', 'name': 'Comfort Ultra Blue 900ml', 'brand': 'Comfort', 'categoryId': 'plastic', 'imageEmoji': '🧺', 'notes': 'HDPE plastic bottle. Recyclable.'},
    {'barcode': '8710908519314', 'name': 'Domestos Bleach 750ml', 'brand': 'Domestos', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'HDPE bottle. Rinse thoroughly before recycling.'},
    {'barcode': '5000112457608', 'name': 'Flash Spray Cleaner 800ml', 'brand': 'Flash', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'HDPE plastic bottle. Remove trigger pump if non-recyclable.'},
    {'barcode': '5000158069503', 'name': 'Dettol Surface Cleaner Spray 750ml', 'brand': 'Dettol', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'HDPE bottle. Rinse and recycle in plastic bin.'},
    {'barcode': '8001090150240', 'name': 'Lenor Fabric Conditioner 1.75L', 'brand': 'Lenor', 'categoryId': 'plastic', 'imageEmoji': '🧺', 'notes': 'HDPE plastic bottle. Rinse and recycle.'},
    {'barcode': '8710522603831', 'name': 'Cif Cream Cleaner 500ml', 'brand': 'Cif', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'HDPE bottle. Rinse and recycle.'},
    {'barcode': '5010724524450', 'name': 'Method All-Purpose Cleaner 828ml', 'brand': 'Method', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': '100% recycled plastic bottle. Rinse and recycle.'},

    // ── Personal Care & Toiletries – Plastic & Metal ──
    {'barcode': '4006381333931', 'name': 'NIVEA Body Lotion 400ml', 'brand': 'NIVEA', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE #2 bottle. Rinse and recycle.'},
    {'barcode': '5000112476875', 'name': 'Head & Shoulders Shampoo 250ml', 'brand': 'Head & Shoulders', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE plastic bottle. Recycle when empty.'},
    {'barcode': '8714789936924', 'name': 'Dove Body Wash 250ml', 'brand': 'Dove', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'PET bottle. Rinse and recycle.'},
    {'barcode': '3574660239720', 'name': 'L\'Oreal Elvive Shampoo 400ml', 'brand': 'L\'Oreal', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE plastic bottle. Recycle when empty.'},
    {'barcode': '3600521328117', 'name': 'Garnier Micellar Water 400ml', 'brand': 'Garnier', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE bottle. Recycle in plastic bin.'},
    {'barcode': '3614271290984', 'name': 'Dove Deo Roll-On 50ml', 'brand': 'Dove', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'HDPE plastic bottle. Rinse and recycle.'},
    {'barcode': '8714789843384', 'name': 'Axe / Lynx Africa Deodorant Spray', 'brand': 'Axe/Lynx', 'categoryId': 'metal', 'imageEmoji': '💨', 'notes': 'Aerosol can. Must be empty before recycling.'},
    {'barcode': '5010622005020', 'name': 'Carex Antibacterial Handwash 250ml', 'brand': 'Carex', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'PET bottle. Rinse. Remove pump dispenser.'},
    {'barcode': '5010123714656', 'name': 'Radox Feel Refreshed Shower Gel', 'brand': 'Radox', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'Plastic bottle. Rinse and place in recycling bin.'},
    {'barcode': '7702018600014', 'name': 'Gillette Fusion Shaving Gel 200ml', 'brand': 'Gillette', 'categoryId': 'metal', 'imageEmoji': '🪒', 'notes': 'Aerosol can. Empty fully before recycling in metal bin.'},
    {'barcode': '5010123700017', 'name': 'Simple Kind to Skin Face Wash', 'brand': 'Simple', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'Plastic squeeze tube. Check locally or general waste.'},

    // ── E-Waste & Tech ──
    {'barcode': '0194252764756', 'name': 'Apple 20W USB-C Power Adapter', 'brand': 'Apple', 'categoryId': 'ewaste', 'imageEmoji': '🔌', 'notes': 'Electronic accessory. Take to e-waste drop-off. Do not bin.'},
    {'barcode': '0194252561560', 'name': 'Samsung USB-C Fast Charging Cable', 'brand': 'Samsung', 'categoryId': 'ewaste', 'imageEmoji': '🔌', 'notes': 'Electronic cable. Recycle at dedicated e-waste point.'},
    {'barcode': '0885909950805', 'name': 'Apple EarPods with Lightning', 'brand': 'Apple', 'categoryId': 'ewaste', 'imageEmoji': '🎧', 'notes': 'Electronic accessory. Take to e-waste collection.'},
    {'barcode': '0012502009767', 'name': 'Energizer AA Batteries 4pk', 'brand': 'Energizer', 'categoryId': 'ewaste', 'imageEmoji': '🔋', 'notes': 'NEVER bin batteries. Take to supermarket or battery drop-off.'},
    {'barcode': '0039800005441', 'name': 'Duracell AAA Batteries 4pk', 'brand': 'Duracell', 'categoryId': 'ewaste', 'imageEmoji': '🔋', 'notes': 'Hazardous waste. Must go to dedicated battery drop-off only.'},
    {'barcode': '0766623030022', 'name': 'AmazonBasics High-Speed HDMI Cable', 'brand': 'Amazon', 'categoryId': 'ewaste', 'imageEmoji': '🔌', 'notes': 'Electronic cable. Recycle at designated e-waste point.'},
    {'barcode': '5099206064736', 'name': 'Logitech M185 Wireless Mouse', 'brand': 'Logitech', 'categoryId': 'ewaste', 'imageEmoji': '🖱️', 'notes': 'E-waste. Remove battery first. Recycle at e-waste depot.'},
    {'barcode': '0619659102456', 'name': 'SanDisk Ultra 64GB USB Drive', 'brand': 'SanDisk', 'categoryId': 'ewaste', 'imageEmoji': '💾', 'notes': 'Small electronic device. Recycle at e-waste collection.'},
    {'barcode': '0085854221115', 'name': 'Anker PowerLine+ USB-C Cable', 'brand': 'Anker', 'categoryId': 'ewaste', 'imageEmoji': '🔌', 'notes': 'Electronic accessory. Take to e-waste bin.'},

    // ── Fresh Produce & Organic ──
    {'barcode': '5000080020027', 'name': 'Tesco Braeburn Apples 6pk', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🍎', 'notes': 'Fruit — organic waste. Compost at home or food waste bin.'},
    {'barcode': '5000080017027', 'name': 'Tesco Bananas 5pk', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🍌', 'notes': 'Organic food waste. Compost peels and organic matter.'},
    {'barcode': '5000080025022', 'name': 'Tesco Baby Spinach 200g', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🥬', 'notes': 'Organic waste. Compost wilted leaves. Bag — soft plastic recycling.'},
    {'barcode': '5000080014026', 'name': 'Tesco Carrots 1kg', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🥕', 'notes': 'Vegetable — organic waste. Compost peelings.'},
    {'barcode': '5000080021024', 'name': 'Tesco White Mushrooms 400g', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🍄', 'notes': 'Organic waste. 100% compostable.'},
    {'barcode': '5010044000801', 'name': 'Warburtons Toastie White Bread 800g', 'brand': 'Warburtons', 'categoryId': 'organic', 'imageEmoji': '🍞', 'notes': 'Stale bread to food waste. Bread bag — recycle at supermarket.'},
    {'barcode': '5010044000818', 'name': 'Hovis Soft White Bread 800g', 'brand': 'Hovis', 'categoryId': 'organic', 'imageEmoji': '🍞', 'notes': 'Food waste to organic bin. Plastic bag — soft plastics collection.'},

    // ── General Waste & Composite Packaging ──
    {'barcode': '7622300489434', 'name': 'Oreo Cookies 154g', 'brand': 'Oreo', 'categoryId': 'general', 'imageEmoji': '🍪', 'notes': 'Multi-layer metallised plastic wrap — not recyclable. General waste.'},
    {'barcode': '5000168013218', 'name': 'Cadbury Dairy Milk 45g', 'brand': 'Cadbury', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film wrapper — general waste.'},
    {'barcode': '5000193001031', 'name': 'Walkers Crisps Ready Salted', 'brand': 'Walkers', 'categoryId': 'general', 'imageEmoji': '🥨', 'notes': 'Metallised plastic foil packet — not curbside recyclable.'},
    {'barcode': '4005900380906', 'name': 'Pringles Original 165g', 'brand': 'Pringles', 'categoryId': 'general', 'imageEmoji': '🥔', 'notes': 'Composite cardboard/metal/plastic tube — general waste.'},
    {'barcode': '8000500310427', 'name': 'Ferrero Rocher T-16', 'brand': 'Ferrero', 'categoryId': 'general', 'imageEmoji': '🍬', 'notes': 'Mixed plastic and foil packaging — general waste.'},
    {'barcode': '4009900030397', 'name': 'Haribo Goldbears 200g', 'brand': 'Haribo', 'categoryId': 'general', 'imageEmoji': '🍬', 'notes': 'Plastic film bag — general waste.'},
    {'barcode': '5000159407236', 'name': 'McVitie\'s Digestives 400g', 'brand': 'McVitie\'s', 'categoryId': 'general', 'imageEmoji': '🍪', 'notes': 'Plastic film wrapper — general waste.'},
    {'barcode': '5000112465085', 'name': 'Kit Kat 4 Finger', 'brand': 'Nestlé', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic wrapper — general waste.'},
    {'barcode': '5000112624182', 'name': 'Mars Bar 51g', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film wrapper — general waste.'},
    {'barcode': '5000112480803', 'name': 'Twix Twin Bars 50g', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film wrapper — general waste.'},
    {'barcode': '5000112462589', 'name': 'Snickers 50g', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film — general waste.'},
    {'barcode': '5000112463678', 'name': 'Bounty 57g', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film wrapper — general waste.'},
    {'barcode': '5012013010025', 'name': 'Oral-B Toothpaste 75ml Tube', 'brand': 'Oral-B', 'categoryId': 'general', 'imageEmoji': '🦷', 'notes': 'Laminated multi-layer plastic tube — general waste.'},
    {'barcode': '5010605021122', 'name': 'Pampers Active Fit Nappies', 'brand': 'Pampers', 'categoryId': 'general', 'imageEmoji': '👶', 'notes': 'Nappies are NOT recyclable. General waste only.'},
    {'barcode': '4053400077688', 'name': 'Ziploc Sandwich Bags', 'brand': 'Ziploc', 'categoryId': 'general', 'imageEmoji': '🛍️', 'notes': 'Plastic bags. Check supermarket soft plastic collection.'},
    {'barcode': '0041540310793', 'name': 'Glad Trash Bags 30pk', 'brand': 'Glad', 'categoryId': 'general', 'imageEmoji': '🛍️', 'notes': 'Plastic bag roll — general waste.'},
    {'barcode': '0078742037134', 'name': 'Scotch Brite Sponge 3pk', 'brand': '3M', 'categoryId': 'general', 'imageEmoji': '🧽', 'notes': 'Synthetic sponge — not recyclable. General waste.'},
  ];


  static final List<String> ecoTips = [
    'Rinse plastic bottles and containers before putting them in the recycling bin.',
    'Recycling one tonne of paper saves 17 trees and 7,000 gallons of water.',
    'A dripping tap can waste up to 20 litres of water per day. Fix it!',
    'Aluminium cans can be back on the shelf as a new product in just 60 days.',
    'Bring reusable bags when shopping to reduce single-use plastic waste.',
    'Switching to LED bulbs uses 75% less energy than traditional incandescent bulbs.',
    'Composting food scraps can reduce your household landfill waste by up to 30%.',
    'Never put batteries in the general waste — take them to a collection point.',
    'Old phones contain gold, silver, and copper — recycle your e-waste!',
    'Cutting your shower by 2 minutes saves around 15 litres of water.',
    'Glass can be recycled endlessly without losing quality.',
    'Empty your containers fully before recycling — even a small amount of product causes contamination.',
    'Greasy pizza boxes cannot be recycled — tear off and recycle the clean top half.',
    'Coffee pods are hard to recycle — consider switching to a reusable cup or pod.',
    'Growing herbs at home reduces packaging waste from store-bought herbs.',
    'Wrapping paper with glitter or foil is not recyclable — opt for plain paper or fabric.',
    'Carpooling just twice a week can reduce your carbon footprint by up to 1,590 lbs of CO₂ per year.',
    'Washing clothes at 30°C rather than 60°C uses 60% less energy.',
    'Buying local and seasonal produce reduces food miles and supports local farmers.',
    'Flatten cardboard boxes before putting them in the recycling bin to save space.',
    'Never pour cooking oil down the drain — it clogs pipes and harms waterways.',
    'Planting flowers like lavender and sunflowers helps support bee populations.',
    'Refill your cleaning product bottles instead of buying new ones to reduce plastic.',
    'Old newspapers can be used as eco-friendly wrapping paper.',
    'Unplug chargers and electronics when not in use to save phantom energy.',
    'Use natural cleaning products like lemon juice and vinegar to reduce chemical waste.',
    'Buying in bulk reduces packaging waste per item.',
    'Start a window herb garden — even a small one makes a difference!',
    'Donate old clothes instead of throwing them away — one person\'s trash is another\'s treasure.',
    'Insulating your home properly can reduce your heating bill by up to 25%.',
  ];
}
