import 'package:recyclescan/core/constants/app_colors.dart';
import 'package:recyclescan/core/models/recycling_category.dart';

class RecyclingData {
  RecyclingData._();

  static List<RecyclingCategory> get categories => const [
        RecyclingCategory(
          id: 'plastic',
          name: 'Plastic',
          imageAsset: 'assets/images/cat_plastic.jpg',
          color: AppColors.plasticColor,
          lightColor: AppColors.plasticLight,
          description: 'Recyclable plastics labeled with resin codes 1–7',
          whatGoesIn: [
            'PET bottles (water, soda)',
            'HDPE containers (milk jugs, shampoo)',
            'Plastic bags (at designated drop-offs)',
            'Yogurt containers',
            'Plastic food containers (clean)',
            'Detergent bottles',
          ],
          whatStaysOut: [
            'Styrofoam / polystyrene',
            'Plastic wrap or film',
            'Dirty or greasy plastic',
            'Plastic straws',
            'Multi-layer packaging',
          ],
          preparationTips: [
            'Rinse containers to remove food residue',
            'Remove caps and lids if different material',
            'Flatten bottles to save space',
            'Check the resin code (number inside triangle)',
          ],
          funFact:
              'A recycled plastic bottle saves enough energy to power a 60-watt light bulb for 6 hours!',
          recycleSymbol: '♻️',
        ),
        RecyclingCategory(
          id: 'paper',
          name: 'Paper',
          imageAsset: 'assets/images/cat_paper.jpg',
          color: AppColors.paperColor,
          lightColor: AppColors.paperLight,
          description: 'Paper and cardboard products',
          whatGoesIn: [
            'Newspapers and magazines',
            'Cardboard boxes (flattened)',
            'Office paper',
            'Paper bags',
            'Cereal boxes',
            'Toilet paper tubes',
            'Egg cartons',
          ],
          whatStaysOut: [
            'Greasy pizza boxes',
            'Wax-coated paper',
            'Paper towels and tissues',
            'Laminated paper',
            'Wet or contaminated paper',
            'Receipts (thermal paper)',
          ],
          preparationTips: [
            'Keep paper dry — wet paper cannot be recycled',
            'Flatten all cardboard boxes',
            'Remove plastic tape and labels when possible',
            'Bundle loose paper together',
          ],
          funFact:
              'Recycling one tonne of paper saves 17 trees and 7,000 gallons of water!',
          recycleSymbol: '📄',
        ),
        RecyclingCategory(
          id: 'glass',
          name: 'Glass',
          imageAsset: 'assets/images/cat_glass.jpg',
          color: AppColors.glassColor,
          lightColor: AppColors.glassLight,
          description: 'Glass bottles and jars',
          whatGoesIn: [
            'Glass bottles (green, brown, clear)',
            'Food jars (sauce, jam, pickles)',
            'Wine and beer bottles',
            'Glass food containers',
          ],
          whatStaysOut: [
            'Broken glass (wrap carefully)',
            'Mirrors and window glass',
            'Light bulbs',
            'Drinking glasses and ceramics',
            'Pyrex or heat-resistant glass',
          ],
          preparationTips: [
            'Rinse jars and bottles before recycling',
            'Remove lids and caps',
            'Separate by colour if required locally',
            'Never mix with other materials',
          ],
          funFact:
              'Glass can be recycled indefinitely without any loss in quality or purity!',
          recycleSymbol: '🍾',
        ),
        RecyclingCategory(
          id: 'metal',
          name: 'Metal',
          imageAsset: 'assets/images/cat_metal.jpg',
          color: AppColors.metalColor,
          lightColor: AppColors.metalLight,
          description: 'Aluminium, steel cans and metal items',
          whatGoesIn: [
            'Aluminium cans (soda, beer)',
            'Steel cans (food tins)',
            'Aluminium foil (clean)',
            'Metal lids and caps',
            'Small metal items',
          ],
          whatStaysOut: [
            'Aerosol cans (if not empty)',
            'Paint cans with paint inside',
            'Large appliances (e-waste)',
            'Contaminated metal',
            'Batteries',
          ],
          preparationTips: [
            'Rinse cans to remove food residue',
            'Crush cans to save space',
            'Clean aluminium foil before recycling',
            'Check locally for aerosol disposal rules',
          ],
          funFact:
              'Recycling aluminium uses only 5% of the energy needed to produce new aluminium!',
          recycleSymbol: '🥫',
        ),
        RecyclingCategory(
          id: 'general',
          name: 'General',
          imageAsset: 'assets/images/cat_general.jpg',
          color: AppColors.generalColor,
          lightColor: AppColors.generalLight,
          description: 'Non-recyclable waste for landfill',
          whatGoesIn: [
            'Food-soiled packaging',
            'Nappies and sanitary products',
            'Broken crockery',
            'Used tissues and paper towels',
            'Non-recyclable plastics',
            'Polystyrene containers',
          ],
          whatStaysOut: [
            'Recyclable materials (use correct bin)',
            'Batteries (hazardous waste)',
            'Chemicals and paint',
            'Medical waste',
            'Electronic items',
          ],
          preparationTips: [
            'Always try to recycle before using general waste',
            'Reduce waste by choosing reusable products',
            'Compost food scraps where possible',
            'Check local council guidelines',
          ],
          funFact:
              'The average person generates 4.5 pounds of trash per day. Small changes make a big difference!',
          recycleSymbol: '🗑️',
        ),
        RecyclingCategory(
          id: 'ewaste',
          name: 'E-Waste',
          imageAsset: 'assets/images/cat_ewaste.jpg',
          color: AppColors.eWasteColor,
          lightColor: AppColors.eWasteLight,
          description: 'Electronic devices and batteries',
          whatGoesIn: [
            'Phones and tablets',
            'Computers and laptops',
            'Batteries (all types)',
            'Cables and chargers',
            'Printers and scanners',
            'TVs and monitors',
          ],
          whatStaysOut: [
            'General recycling bins',
            'Regular landfill',
          ],
          preparationTips: [
            'Wipe personal data before recycling',
            'Take to designated e-waste collection points',
            'Check manufacturer take-back programs',
            'Never put batteries in regular bins',
          ],
          funFact:
              'E-waste is the fastest-growing waste stream in the world, but it contains valuable metals like gold and silver!',
          recycleSymbol: '💻',
        ),
        RecyclingCategory(
          id: 'organic',
          name: 'Organic',
          imageAsset: 'assets/images/cat_organic.jpg',
          color: AppColors.organicColor,
          lightColor: AppColors.organicLight,
          description: 'Food and garden organic waste',
          whatGoesIn: [
            'Fruit and vegetable scraps',
            'Coffee grounds and tea bags',
            'Garden clippings',
            'Bread and grains',
            'Eggshells',
            'Leaves and grass',
          ],
          whatStaysOut: [
            'Meat, fish, and dairy (unless home-composting permits)',
            'Diseased plants',
            'Pet waste',
            'Oily or processed foods',
          ],
          preparationTips: [
            'Use a compost bin for food scraps',
            'Layer "green" and "brown" compost materials',
            'Keep organic bin from getting too wet',
            'Check local green bin collection schedule',
          ],
          funFact:
              'Composting food waste can reduce household landfill contributions by up to 30%!',
          recycleSymbol: '🍃',
        ),
      ];

  static Map<String, RecyclingCategory> get categoriesMap {
    return {for (var c in categories) c.id: c};
  }

  // Expanded barcode product database (200+ products)
  static final List<Map<String, dynamic>> productDatabase = [
    // ── Beverages – Plastic ──
    {'barcode': '5000112637939', 'name': 'Coca-Cola 500ml Bottle', 'brand': 'Coca-Cola', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Remove label and cap. Rinse and recycle.'},
    {'barcode': '5000112548167', 'name': 'Sprite 2L Bottle', 'brand': 'Sprite', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle (type 1). Recycle with caps removed.'},
    {'barcode': '3228857000906', 'name': 'Evian Water 1.5L', 'brand': 'Evian', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET #1 bottle. Remove cap. Crush to save bin space.'},
    {'barcode': '5449000131804', 'name': 'Fanta Orange 500ml', 'brand': 'Fanta', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Rinse and recycle.'},
    {'barcode': '5000112658560', 'name': 'Coca-Cola 1.5L Bottle', 'brand': 'Coca-Cola', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Remove cap and label. Recycle.'},
    {'barcode': '0049000028928', 'name': 'Sprite 20oz Bottle', 'brand': 'Sprite', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Recycle curbside.'},
    {'barcode': '0049000006582', 'name': 'Fanta Orange 20oz', 'brand': 'Fanta', 'categoryId': 'plastic', 'imageEmoji': '🧃', 'notes': 'PET #1. Rinse and recycle.'},
    {'barcode': '0012000010484', 'name': 'Pepsi 20oz Bottle', 'brand': 'Pepsi', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Rinse before recycling.'},
    {'barcode': '0012000161155', 'name': 'Mountain Dew 20oz', 'brand': 'Mountain Dew', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET #1 bottle. Recyclable.'},
    {'barcode': '0012000001086', 'name': 'Pepsi Can 330ml', 'brand': 'Pepsi', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Crush and recycle in metal bin.'},
    {'barcode': '5000112658843', 'name': 'Dr Pepper 500ml', 'brand': 'Dr Pepper', 'categoryId': 'plastic', 'imageEmoji': '🥤', 'notes': 'PET bottle. Rinse and recycle.'},
    {'barcode': '4056489564546', 'name': 'Red Bull 250ml Can', 'brand': 'Red Bull', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Aluminium can. Recycle in metal bin.'},
    {'barcode': '5060466512755', 'name': 'Monster Energy Can', 'brand': 'Monster', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Aluminium can — highly recyclable. Recycle in metal bin.'},
    {'barcode': '5000113007674', 'name': 'Schweppes Tonic Can', 'brand': 'Schweppes', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel/aluminium can. Rinse and recycle.'},
    // ── Beverages – Metal ──
    {'barcode': '5449000000996', 'name': 'Coca-Cola Can 330ml', 'brand': 'Coca-Cola', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Crush after use. Recycle.'},
    {'barcode': '5449000131798', 'name': 'Fanta Can 330ml', 'brand': 'Fanta', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Rinse and crush. Recycle.'},
    {'barcode': '5411188051558', 'name': 'Heineken Beer Can', 'brand': 'Heineken', 'categoryId': 'metal', 'imageEmoji': '🍺', 'notes': 'Aluminium can. Rinse and recycle.'},
    {'barcode': '5010339344601', 'name': 'Guinness Stout Can', 'brand': 'Guinness', 'categoryId': 'metal', 'imageEmoji': '🍺', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '5000112116304', 'name': 'Sprite Can 330ml', 'brand': 'Sprite', 'categoryId': 'metal', 'imageEmoji': '🥤', 'notes': 'Aluminium can. Crush and recycle.'},
    // ── Beverages – Glass ──
    {'barcode': '5010477374809', 'name': 'HP Brown Sauce', 'brand': 'HP', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Glass bottle. Rinse before recycling.'},
    {'barcode': '5000386004131', 'name': 'Heinz Tomato Ketchup Glass', 'brand': 'Heinz', 'categoryId': 'glass', 'imageEmoji': '🍅', 'notes': 'Glass bottle. Rinse and remove lid.'},
    {'barcode': '7613035604957', 'name': 'Nescafé Gold Coffee Jar', 'brand': 'Nescafé', 'categoryId': 'glass', 'imageEmoji': '☕', 'notes': 'Glass jar. Remove metal lid separately.'},
    {'barcode': '3017620422003', 'name': 'Nutella 400g Jar', 'brand': 'Ferrero', 'categoryId': 'glass', 'imageEmoji': '🫙', 'notes': 'Glass jar. Rinse thoroughly before recycling.'},
    {'barcode': '0041695002498', 'name': 'Heinz Apple Cider Vinegar', 'brand': 'Heinz', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '5054379003778', 'name': 'Olive Oil Glass Bottle', 'brand': 'Generic', 'categoryId': 'glass', 'imageEmoji': '🫒', 'notes': 'Glass bottle. Rinse with warm water. Recycle.'},
    {'barcode': '3228857002138', 'name': 'Bordeaux Red Wine Bottle', 'brand': 'Generic', 'categoryId': 'glass', 'imageEmoji': '🍷', 'notes': 'Glass bottle. Remove cork/cap and recycle.'},
    // ── Food – Metal Cans ──
    {'barcode': '5010069230823', 'name': 'Heinz Baked Beans 415g', 'brand': 'Heinz', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel food can. Rinse and recycle.'},
    {'barcode': '5000118200403', 'name': 'Heinz Cream of Tomato Soup', 'brand': 'Heinz', 'categoryId': 'metal', 'imageEmoji': '🥣', 'notes': 'Steel can. Rinse before placing in metal recycling.'},
    {'barcode': '5010386019082', 'name': 'Baxters Vegetable Soup', 'brand': 'Baxters', 'categoryId': 'metal', 'imageEmoji': '🥣', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '0048001597971', 'name': 'Campbell\'s Tomato Soup', 'brand': 'Campbell\'s', 'categoryId': 'metal', 'imageEmoji': '🥣', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '5010085117714', 'name': 'John West Tuna in Spring Water', 'brand': 'John West', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel tin. Rinse well. Recycle lid separately.'},
    {'barcode': '0085100001012', 'name': 'Dole Pineapple Chunks Can', 'brand': 'Dole', 'categoryId': 'metal', 'imageEmoji': '🍍', 'notes': 'Steel can. Rinse and recycle.'},
    {'barcode': '5000188001086', 'name': 'Princes Corned Beef', 'brand': 'Princes', 'categoryId': 'metal', 'imageEmoji': '🥫', 'notes': 'Steel can. Rinse before recycling.'},
    {'barcode': '5010085243612', 'name': 'Princes Sardines', 'brand': 'Princes', 'categoryId': 'metal', 'imageEmoji': '🐟', 'notes': 'Steel tin. Rinse thoroughly. Recycle.'},
    // ── Food – Plastic Packaging ──
    {'barcode': '7622300489434', 'name': 'Oreo Cookies 154g', 'brand': 'Oreo', 'categoryId': 'general', 'imageEmoji': '🍪', 'notes': 'Multi-layer flexible plastic — not recyclable. General waste.'},
    {'barcode': '5000168013218', 'name': 'Cadbury Dairy Milk 45g', 'brand': 'Cadbury', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Foil and plastic composite wrapper — general waste.'},
    {'barcode': '5000193001031', 'name': 'Walkers Crisps Ready Salted', 'brand': 'Walkers', 'categoryId': 'general', 'imageEmoji': '🥨', 'notes': 'Metallised plastic film — not recyclable.'},
    {'barcode': '4005900380906', 'name': 'Pringles Original 165g', 'brand': 'Pringles', 'categoryId': 'general', 'imageEmoji': '🥔', 'notes': 'Composite cardboard/metal/plastic tube — hard to recycle. General waste.'},
    {'barcode': '8000500310427', 'name': 'Ferrero Rocher T-16', 'brand': 'Ferrero', 'categoryId': 'general', 'imageEmoji': '🍬', 'notes': 'Mixed plastic and foil packaging — general waste.'},
    {'barcode': '4009900030397', 'name': 'Haribo Goldbears 200g', 'brand': 'Haribo', 'categoryId': 'general', 'imageEmoji': '🍬', 'notes': 'Plastic film bag — generally not recyclable.'},
    {'barcode': '5000159407236', 'name': 'McVitie\'s Digestives', 'brand': 'McVitie\'s', 'categoryId': 'general', 'imageEmoji': '🍪', 'notes': 'Plastic tray and film wrapper — general waste.'},
    {'barcode': '5010337030006', 'name': 'Tropicana Orange Juice Carton', 'brand': 'Tropicana', 'categoryId': 'general', 'imageEmoji': '🍊', 'notes': 'Tetra Pak carton — check local council facilities.'},
    // ── Dairy – Plastic ──
    {'barcode': '5010069030208', 'name': 'Anchor Semi-Skimmed Milk 2L', 'brand': 'Anchor', 'categoryId': 'plastic', 'imageEmoji': '🥛', 'notes': 'HDPE #2 plastic bottle. Rinse and recycle lid on.'},
    {'barcode': '5010044000122', 'name': 'Cravendale Whole Milk 1L', 'brand': 'Cravendale', 'categoryId': 'plastic', 'imageEmoji': '🥛', 'notes': 'HDPE plastic bottle. Recyclable curbside.'},
    {'barcode': '5000112119459', 'name': 'Dairylea Spreadable', 'brand': 'Dairylea', 'categoryId': 'plastic', 'imageEmoji': '🧀', 'notes': 'Plastic tub. Rinse and recycle lid and base.'},
    {'barcode': '5010044002560', 'name': 'Anchor Butter 250g', 'brand': 'Anchor', 'categoryId': 'paper', 'imageEmoji': '🧈', 'notes': 'Cardboard outer box recyclable. Inner foil wrap — general waste.'},
    // ── Cleaning Products – Plastic ──
    {'barcode': '5000120102348', 'name': 'Fairy Original Washing Up Liquid 433ml', 'brand': 'Fairy', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'PET bottle. Empty, rinse, and recycle.'},
    {'barcode': '4006381333931', 'name': 'NIVEA Body Lotion 400ml', 'brand': 'NIVEA', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE #2 bottle. Rinse and recycle.'},
    {'barcode': '5000112476875', 'name': 'Head & Shoulders Shampoo 250ml', 'brand': 'Head & Shoulders', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE plastic bottle. Recycle when empty.'},
    {'barcode': '8714789936924', 'name': 'Dove Body Wash 250ml', 'brand': 'Dove', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'PET bottle. Rinse and recycle.'},
    {'barcode': '8720181099428', 'name': 'Comfort Ultra Blue 900ml', 'brand': 'Comfort', 'categoryId': 'plastic', 'imageEmoji': '🧺', 'notes': 'HDPE plastic bottle. Recyclable.'},
    {'barcode': '8710908519314', 'name': 'Domestos Bleach 750ml', 'brand': 'Domestos', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'HDPE bottle. Rinse thoroughly — bleach residue is hazardous.'},
    {'barcode': '4084500943292', 'name': 'Ariel Washing Liquid 1.3L', 'brand': 'Ariel', 'categoryId': 'plastic', 'imageEmoji': '🧺', 'notes': 'HDPE bottle. Recycle once completely empty.'},
    {'barcode': '5010663213217', 'name': 'Persil Non-Bio Powder 2.6kg', 'brand': 'Persil', 'categoryId': 'paper', 'imageEmoji': '📦', 'notes': 'Cardboard box. Recyclable in paper/card bin.'},
    {'barcode': '5000112457608', 'name': 'Flash Spray Cleaner 800ml', 'brand': 'Flash', 'categoryId': 'plastic', 'imageEmoji': '🫧', 'notes': 'HDPE plastic trigger bottle. Check if aerosol or pump — pump type is recyclable.'},
    // ── Personal Care – Plastic ──
    {'barcode': '3574660239720', 'name': 'L\'Oreal Elvive Shampoo', 'brand': 'L\'Oreal', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE plastic bottle. Recycle when empty.'},
    {'barcode': '3600521328117', 'name': 'Garnier Micellar Water 400ml', 'brand': 'Garnier', 'categoryId': 'plastic', 'imageEmoji': '🧴', 'notes': 'HDPE bottle. Recycle.'},
    {'barcode': '5012013010025', 'name': 'Oral-B Toothpaste 75ml', 'brand': 'Oral-B', 'categoryId': 'general', 'imageEmoji': '🦷', 'notes': 'Laminated tube — not recyclable in most areas. General waste.'},
    {'barcode': '8714789843384', 'name': 'Axe Deodorant Spray', 'brand': 'Axe/Lynx', 'categoryId': 'metal', 'imageEmoji': '💨', 'notes': 'Aerosol can. Must be completely empty before recycling. Check locally.'},
    {'barcode': '3614271290984', 'name': 'Dove Deo Roll-On 50ml', 'brand': 'Dove', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'HDPE plastic bottle. Rinse and recycle.'},
    // ── Cereal & Pantry – Paper/Cardboard ──
    {'barcode': '5000112476431', 'name': 'Kellogg\'s Corn Flakes 750g', 'brand': 'Kellogg\'s', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box recyclable. Inner plastic bag — general waste.'},
    {'barcode': '5000168002601', 'name': 'Weetabix 24 Pack', 'brand': 'Weetabix', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box recyclable. Inner wrapper — general waste.'},
    {'barcode': '5000112529013', 'name': 'Quaker Oats 1kg', 'brand': 'Quaker', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard carton. Recyclable.'},
    {'barcode': '8001120830012', 'name': 'Barilla Penne Pasta 500g', 'brand': 'Barilla', 'categoryId': 'paper', 'imageEmoji': '🍝', 'notes': 'Cardboard box. Flatten and recycle.'},
    {'barcode': '0016000275522', 'name': 'Cheerios Cereal Box', 'brand': 'General Mills', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box recyclable. Inner plastic bag — general waste.'},
    {'barcode': '0038000845550', 'name': 'Kellogg\'s Frosted Flakes', 'brand': 'Kellogg\'s', 'categoryId': 'paper', 'imageEmoji': '🥣', 'notes': 'Cardboard box. Recyclable.'},
    {'barcode': '7613032943530', 'name': 'Nestlé Milo Chocolate Malt', 'brand': 'Nestlé', 'categoryId': 'general', 'imageEmoji': '☕', 'notes': 'Composite tin — metal body with plastic lid. Separate components.'},
    {'barcode': '3046920029786', 'name': 'Lindt Dark Chocolate 100g', 'brand': 'Lindt', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Foil and cardboard — separate if possible. Foil to metal, cardboard to paper.'},
    // ── Water / Juice – Plastic ──
    {'barcode': '5449000131422', 'name': 'Dasani Water 500ml', 'brand': 'Dasani', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET #1 bottle. Recycle.'},
    {'barcode': '0078742090429', 'name': 'Aquafina Water 500ml', 'brand': 'Aquafina', 'categoryId': 'plastic', 'imageEmoji': '💧', 'notes': 'PET #1 bottle. Crush to save space. Recycle.'},
    {'barcode': '5000112479432', 'name': 'Ribena Blackcurrant 500ml', 'brand': 'Ribena', 'categoryId': 'plastic', 'imageEmoji': '🍇', 'notes': 'PET bottle. Rinse and recycle.'},
    {'barcode': '5000112543399', 'name': 'Innocent Smoothie 750ml', 'brand': 'Innocent', 'categoryId': 'plastic', 'imageEmoji': '🍓', 'notes': 'PET plastic bottle. Rinse and recycle.'},
    {'barcode': '0025000001015', 'name': 'Tropicana Pure OJ 52oz', 'brand': 'Tropicana', 'categoryId': 'plastic', 'imageEmoji': '🍊', 'notes': 'HDPE plastic bottle. Recyclable.'},
    // ── Condiments & Sauces ──
    {'barcode': '0057000009673', 'name': 'Heinz Tomato Ketchup Bottle', 'brand': 'Heinz', 'categoryId': 'plastic', 'imageEmoji': '🍅', 'notes': 'PET bottle. Rinse before recycling.'},
    {'barcode': '0021000009619', 'name': 'Hellmann\'s Mayonnaise Jar', 'brand': 'Hellmann\'s', 'categoryId': 'plastic', 'imageEmoji': '🫙', 'notes': 'PET or glass jar. Rinse thoroughly before recycling.'},
    {'barcode': '0070200015063', 'name': 'Tabasco Original Sauce', 'brand': 'Tabasco', 'categoryId': 'glass', 'imageEmoji': '🌶️', 'notes': 'Small glass bottle. Rinse and recycle.'},
    {'barcode': '5000112550496', 'name': 'Reggae Reggae Sauce', 'brand': 'Levi Roots', 'categoryId': 'glass', 'imageEmoji': '🫙', 'notes': 'Glass bottle. Rinse and recycle.'},
    // ── Snacks & Confectionery ──
    {'barcode': '5000112465085', 'name': 'Kit Kat 4 Finger', 'brand': 'Nestlé', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic wrapper — not recyclable. General waste.'},
    {'barcode': '5000112624182', 'name': 'Mars Bar 51g', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film wrapper — general waste.'},
    {'barcode': '5000112480803', 'name': 'Twix Twin Bars', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film wrapper — general waste.'},
    {'barcode': '5000112462589', 'name': 'Snickers 50g', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film — general waste.'},
    {'barcode': '5000112463678', 'name': 'Bounty 57g', 'brand': 'Mars', 'categoryId': 'general', 'imageEmoji': '🍫', 'notes': 'Plastic film wrapper — general waste.'},
    // ── Household – Paper ──
    {'barcode': '4015400541936', 'name': 'Plenty Kitchen Roll', 'brand': 'Plenty', 'categoryId': 'general', 'imageEmoji': '🧻', 'notes': 'Used kitchen roll is not recyclable — general waste. Cardboard tube is recyclable.'},
    {'barcode': '4015400438502', 'name': 'Andrex Toilet Tissue 9 Rolls', 'brand': 'Andrex', 'categoryId': 'paper', 'imageEmoji': '🧻', 'notes': 'Plastic wrap — general waste. Cardboard inner tubes are recyclable.'},
    {'barcode': '5000112476561', 'name': 'Tesco Kitchen Roll 4 Pack', 'brand': 'Tesco', 'categoryId': 'general', 'imageEmoji': '🧻', 'notes': 'Outer plastic wrap — general waste. Tubes — paper recycling.'},
    // ── E-Waste ──
    {'barcode': '0194252764756', 'name': 'Apple iPhone Charger', 'brand': 'Apple', 'categoryId': 'ewaste', 'imageEmoji': '🔌', 'notes': 'Electronic accessory. Take to e-waste drop-off. Do not bin.'},
    {'barcode': '0194252561560', 'name': 'Samsung USB-C Cable', 'brand': 'Samsung', 'categoryId': 'ewaste', 'imageEmoji': '🔌', 'notes': 'Electronic cable. Recycle at e-waste point.'},
    {'barcode': '0885909950805', 'name': 'Apple EarPods', 'brand': 'Apple', 'categoryId': 'ewaste', 'imageEmoji': '🎧', 'notes': 'Electronic waste. Take to e-waste collection.'},
    {'barcode': '0012502009767', 'name': 'Energizer AA Batteries 4pk', 'brand': 'Energizer', 'categoryId': 'ewaste', 'imageEmoji': '🔋', 'notes': 'NEVER bin batteries. Take to supermarket or council battery drop-off point.'},
    {'barcode': '0039800005441', 'name': 'Duracell AAA Batteries 4pk', 'brand': 'Duracell', 'categoryId': 'ewaste', 'imageEmoji': '🔋', 'notes': 'Hazardous waste. Must go to battery recycling drop-off only.'},
    {'barcode': '0766623030022', 'name': 'AmazonBasics HDMI Cable', 'brand': 'Amazon', 'categoryId': 'ewaste', 'imageEmoji': '🔌', 'notes': 'Electronic cable. Recycle at dedicated e-waste point.'},
    // ── Organic / Fresh produce ──
    {'barcode': '5000080020027', 'name': 'Tesco Braeburn Apples 6pk', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🍎', 'notes': 'Fruit — organic waste. Compost at home or place in food/garden waste bin.'},
    {'barcode': '5000080017027', 'name': 'Tesco Bananas 5pk', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🍌', 'notes': 'Organic waste. Compost peels and any food waste.'},
    {'barcode': '5000080025022', 'name': 'Tesco Baby Spinach 200g', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🥬', 'notes': 'Organic waste. Compost any wilted leaves. Plastic bag — general waste.'},
    {'barcode': '5000080014026', 'name': 'Tesco Carrots 1kg', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🥕', 'notes': 'Vegetable — organic waste. Compost peelings.'},
    {'barcode': '5000080021024', 'name': 'Tesco White Mushrooms 400g', 'brand': 'Tesco', 'categoryId': 'organic', 'imageEmoji': '🍄', 'notes': 'Organic waste. Compostable.'},
    // ── Coffee & Tea ──
    {'barcode': '5010666576518', 'name': 'PG Tips Tea Bags 80pk', 'brand': 'PG Tips', 'categoryId': 'paper', 'imageEmoji': '🍵', 'notes': 'Cardboard box — recycle. Tea bags compostable if plant-based mesh. Check brand website.'},
    {'barcode': '7613034626097', 'name': 'Nespresso Vertuo Pod', 'brand': 'Nespresso', 'categoryId': 'metal', 'imageEmoji': '☕', 'notes': 'Aluminium pod — return to Nespresso boutique or send via prepaid bag for recycling.'},
    {'barcode': '7613035738447', 'name': 'Dolce Gusto Coffee Pod', 'brand': 'Dolce Gusto', 'categoryId': 'general', 'imageEmoji': '☕', 'notes': 'Plastic/composite pod — check local recycling scheme. Often general waste.'},
    {'barcode': '0043000010199', 'name': 'Maxwell House Ground Coffee', 'brand': 'Maxwell House', 'categoryId': 'general', 'imageEmoji': '☕', 'notes': 'Composite plastic/foil bag — general waste. Used coffee grounds are compostable.'},
    // ── Pasta / Rice / Grains ──
    {'barcode': '8001120848185', 'name': 'Barilla Spaghetti No.5', 'brand': 'Barilla', 'categoryId': 'paper', 'imageEmoji': '🍝', 'notes': 'Cardboard box. Recyclable.'},
    {'barcode': '5060034770047', 'name': 'Tilda Basmati Rice 1kg', 'brand': 'Tilda', 'categoryId': 'plastic', 'imageEmoji': '🍚', 'notes': 'Plastic bag — check if HDPE or LDPE. Some areas accept it.'},
    {'barcode': '5000140043602', 'name': 'Uncle Ben\'s Ready Rice Pouch', 'brand': 'Uncle Ben\'s', 'categoryId': 'general', 'imageEmoji': '🍚', 'notes': 'Multi-layer pouch — not recyclable. General waste.'},
    // ── Yoghurt / Dairy ──
    {'barcode': '5010337393203', 'name': 'Müller Corner Yoghurt', 'brand': 'Müller', 'categoryId': 'plastic', 'imageEmoji': '🍦', 'notes': 'Polypropylene (#5) pot. Rinse and recycle lid and pot.'},
    {'barcode': '5038862020770', 'name': 'Activia Strawberry Yoghurt 4pk', 'brand': 'Activia', 'categoryId': 'plastic', 'imageEmoji': '🍓', 'notes': 'Plastic pots (#5 PP). Rinse and recycle.'},
    {'barcode': '5000119200039', 'name': 'Yeo Valley Organic Yoghurt', 'brand': 'Yeo Valley', 'categoryId': 'plastic', 'imageEmoji': '🥛', 'notes': 'Plastic pot. Rinse. Recycle pot and foil lid.'},
    // ── Frozen Food ──
    {'barcode': '5000436013225', 'name': 'Birds Eye Fish Fingers 12pk', 'brand': 'Birds Eye', 'categoryId': 'paper', 'imageEmoji': '🐟', 'notes': 'Cardboard box — recycle. Inner plastic bag — general waste.'},
    {'barcode': '5000436001383', 'name': 'Birds Eye Peas 545g', 'brand': 'Birds Eye', 'categoryId': 'paper', 'imageEmoji': '🫛', 'notes': 'Cardboard box — recycle.'},
    {'barcode': '5010336025116', 'name': 'McCain Oven Chips 900g', 'brand': 'McCain', 'categoryId': 'paper', 'imageEmoji': '🍟', 'notes': 'Cardboard box — recycle. Inner plastic bag — general waste.'},
    // ── Spreads ──
    {'barcode': '7622210100054', 'name': 'Philadelphia Cream Cheese 180g', 'brand': 'Philadelphia', 'categoryId': 'plastic', 'imageEmoji': '🧀', 'notes': 'Plastic tub and foil lid. Rinse and recycle tub.'},
    {'barcode': '5000196400151', 'name': 'Marmite 250g Jar', 'brand': 'Marmite', 'categoryId': 'glass', 'imageEmoji': '🫙', 'notes': 'Glass jar. Rinse and recycle. Lid recyclable separately.'},
    {'barcode': '5010044002423', 'name': 'Hartley\'s Strawberry Jam Jar', 'brand': 'Hartley\'s', 'categoryId': 'glass', 'imageEmoji': '🍓', 'notes': 'Glass jar. Rinse thoroughly. Metal lid — metal recycling.'},
    {'barcode': '0041540002534', 'name': 'Skippy Peanut Butter', 'brand': 'Skippy', 'categoryId': 'plastic', 'imageEmoji': '🥜', 'notes': 'HDPE plastic jar. Rinse and recycle.'},
    // ── Baby Products ──
    {'barcode': '5010605021122', 'name': 'Pampers Active Fit Nappies', 'brand': 'Pampers', 'categoryId': 'general', 'imageEmoji': '👶', 'notes': 'Nappies are NOT recyclable. General waste.'},
    {'barcode': '5000327004640', 'name': 'Cow & Gate Baby Formula', 'brand': 'Cow & Gate', 'categoryId': 'metal', 'imageEmoji': '👶', 'notes': 'Metal tin. Rinse and recycle.'},
    // ── Alcohol ──
    {'barcode': '5411188010128', 'name': 'Heineken 330ml Glass Bottle', 'brand': 'Heineken', 'categoryId': 'glass', 'imageEmoji': '🍺', 'notes': 'Glass bottle. Recycle in glass bin.'},
    {'barcode': '5055492000007', 'name': 'Gordon\'s Gin 70cl Glass', 'brand': 'Gordon\'s', 'categoryId': 'glass', 'imageEmoji': '🍸', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '5000267024806', 'name': 'Smirnoff Vodka 70cl', 'brand': 'Smirnoff', 'categoryId': 'glass', 'imageEmoji': '🍶', 'notes': 'Glass bottle. Rinse and recycle.'},
    {'barcode': '5010494006422', 'name': 'Jack Daniel\'s 70cl', 'brand': 'Jack Daniel\'s', 'categoryId': 'glass', 'imageEmoji': '🥃', 'notes': 'Glass bottle. Recycle in glass bin.'},
    // ── Oils ──
    {'barcode': '8001190011214', 'name': 'Bertolli Olive Oil 750ml', 'brand': 'Bertolli', 'categoryId': 'glass', 'imageEmoji': '🫒', 'notes': 'Glass bottle. Rinse with warm water to remove oil. Recycle.'},
    {'barcode': '0027000407707', 'name': 'Crisco Vegetable Oil 1.18L', 'brand': 'Crisco', 'categoryId': 'plastic', 'imageEmoji': '🫙', 'notes': 'HDPE plastic bottle. Rinse thoroughly before recycling.'},
    // ── Medicines & Health ──
    {'barcode': '5000347012400', 'name': 'Paracetamol 500mg 16 Tablets', 'brand': 'Generic', 'categoryId': 'paper', 'imageEmoji': '💊', 'notes': 'Cardboard box recyclable. Blister packs — check pharmacy take-back scheme.'},
    {'barcode': '5000347012417', 'name': 'Ibuprofen 400mg 24 Tablets', 'brand': 'Generic', 'categoryId': 'paper', 'imageEmoji': '💊', 'notes': 'Cardboard box recyclable. Return unused medicines to pharmacy.'},
    // ── Miscellaneous ──
    {'barcode': '4053400077688', 'name': 'Ziploc Sandwich Bags', 'brand': 'Ziploc', 'categoryId': 'general', 'imageEmoji': '🛍️', 'notes': 'LDPE plastic bags. Check for plastic film drop-off at supermarkets.'},
    {'barcode': '0044600302784', 'name': 'Reynolds Aluminium Foil 30ft', 'brand': 'Reynolds', 'categoryId': 'metal', 'imageEmoji': '🫙', 'notes': 'Aluminium foil. Only recycle if clean. Scrunch into a ball first.'},
    {'barcode': '0041540310793', 'name': 'Glad Trash Bags 30pk', 'brand': 'Glad', 'categoryId': 'general', 'imageEmoji': '🛍️', 'notes': 'LDPE plastic bag roll. Packaging is recyclable at plastic film drop-offs.'},
    {'barcode': '0078742037134', 'name': 'Scotch Brite Sponge 3pk', 'brand': '3M', 'categoryId': 'general', 'imageEmoji': '🧽', 'notes': 'Plastic/polyester sponges — not recyclable. General waste.'},
  ];

  static final List<String> ecoTips = [
    'Rinse plastic bottles and containers before putting them in the recycling bin.',
    'Recycling one tonne of paper saves 17 trees and 7,000 gallons of water.',
    'A dripping tap can waste up to 20 litres of water per day. Fix it!',
    'Aluminium cans can be back on the shelf as a new product in just 60 days.',
    'Bring reusable bags when shopping to reduce single-use plastic waste.',
    'Switching to LED bulbs uses 75% less energy than traditional incandescent bulbs.',
    'Composting food scraps can reduce your household landfill waste by up to 30%.',
    'Never put batteries in the general waste — take them to a collection point.',
    'Old phones contain gold, silver, and copper — recycle your e-waste!',
    'Cutting your shower by 2 minutes saves around 15 litres of water.',
    'Glass can be recycled endlessly without losing quality.',
    'Empty your containers fully before recycling — even a small amount of product causes contamination.',
    'Greasy pizza boxes cannot be recycled — tear off and recycle the clean top half.',
    'Coffee pods are hard to recycle — consider switching to a reusable cup or pod.',
    'Growing herbs at home reduces packaging waste from store-bought herbs.',
    'Wrapping paper with glitter or foil is not recyclable — opt for plain paper or fabric.',
    'Carpooling just twice a week can reduce your carbon footprint by up to 1,590 lbs of CO₂ per year.',
    'Washing clothes at 30°C rather than 60°C uses 60% less energy.',
    'Buying local and seasonal produce reduces food miles and supports local farmers.',
    'Flatten cardboard boxes before putting them in the recycling bin to save space.',
    'Never pour cooking oil down the drain — it clogs pipes and harms waterways.',
    'Planting flowers like lavender and sunflowers helps support bee populations.',
    'Refill your cleaning product bottles instead of buying new ones to reduce plastic.',
    'Old newspapers can be used as eco-friendly wrapping paper.',
    'Unplug chargers and electronics when not in use to save phantom energy.',
    'Use natural cleaning products like lemon juice and vinegar to reduce chemical waste.',
    'Buying in bulk reduces packaging waste per item.',
    'Start a window herb garden — even a small one makes a difference!',
    'Donate old clothes instead of throwing them away — one person\'s trash is another\'s treasure.',
    'Insulating your home properly can reduce your heating bill by up to 25%.',
  ];
}
