import 'package:flutter/material.dart';
import 'package:recyclescan/core/constants/app_colors.dart';
import 'package:recyclescan/core/models/recycling_category.dart';

class RecyclingData {
  RecyclingData._();

  static List<RecyclingCategory> get categories => [
        RecyclingCategory(
          id: 'plastic',
          name: 'Plastic',
          icon: Icons.local_drink_outlined,
          color: AppColors.plasticColor,
          lightColor: AppColors.plasticLight,
          description: 'Recyclable plastics labeled with resin codes 1–7',
          whatGoesIn: [
            'PET bottles (water, soda)',
            'HDPE containers (milk jugs, shampoo)',
            'Plastic bags (at designated drop-offs)',
            'Yogurt containers',
            'Plastic food containers (clean)',
            'Detergent bottles',
          ],
          whatStaysOut: [
            'Styrofoam / polystyrene',
            'Plastic wrap or film',
            'Dirty or greasy plastic',
            'Plastic straws',
            'Multi-layer packaging',
          ],
          preparationTips: [
            'Rinse containers to remove food residue',
            'Remove caps and lids if different material',
            'Flatten bottles to save space',
            'Check the resin code (number inside triangle)',
          ],
          funFact:
              'A recycled plastic bottle saves enough energy to power a 60-watt light bulb for 6 hours!',
          recycleSymbol: '♻️',
        ),
        RecyclingCategory(
          id: 'paper',
          name: 'Paper',
          icon: Icons.description_outlined,
          color: AppColors.paperColor,
          lightColor: AppColors.paperLight,
          description: 'Paper and cardboard products',
          whatGoesIn: [
            'Newspapers and magazines',
            'Cardboard boxes (flattened)',
            'Office paper',
            'Paper bags',
            'Cereal boxes',
            'Toilet paper tubes',
            'Egg cartons',
          ],
          whatStaysOut: [
            'Greasy pizza boxes',
            'Wax-coated paper',
            'Paper towels and tissues',
            'Laminated paper',
            'Wet or contaminated paper',
            'Receipts (thermal paper)',
          ],
          preparationTips: [
            'Keep paper dry — wet paper cannot be recycled',
            'Flatten all cardboard boxes',
            'Remove plastic tape and labels when possible',
            'Bundle loose paper together',
          ],
          funFact:
              'Recycling one tonne of paper saves 17 trees and 7,000 gallons of water!',
          recycleSymbol: '📄',
        ),
        RecyclingCategory(
          id: 'glass',
          name: 'Glass',
          icon: Icons.local_bar_outlined,
          color: AppColors.glassColor,
          lightColor: AppColors.glassLight,
          description: 'Glass bottles and jars',
          whatGoesIn: [
            'Glass bottles (green, brown, clear)',
            'Food jars (sauce, jam, pickles)',
            'Wine and beer bottles',
            'Glass food containers',
          ],
          whatStaysOut: [
            'Broken glass (wrap carefully)',
            'Mirrors and window glass',
            'Light bulbs',
            'Drinking glasses and ceramics',
            'Pyrex or heat-resistant glass',
          ],
          preparationTips: [
            'Rinse jars and bottles before recycling',
            'Remove lids and caps',
            'Separate by colour if required locally',
            'Never mix with other materials',
          ],
          funFact:
              'Glass can be recycled indefinitely without any loss in quality or purity!',
          recycleSymbol: '🍾',
        ),
        RecyclingCategory(
          id: 'metal',
          name: 'Metal',
          icon: Icons.compress_outlined,
          color: AppColors.metalColor,
          lightColor: AppColors.metalLight,
          description: 'Aluminium, steel cans and metal items',
          whatGoesIn: [
            'Aluminium cans (soda, beer)',
            'Steel cans (food tins)',
            'Aluminium foil (clean)',
            'Metal lids and caps',
            'Small metal items',
          ],
          whatStaysOut: [
            'Aerosol cans (if not empty)',
            'Paint cans with paint inside',
            'Large appliances (e-waste)',
            'Contaminated metal',
            'Batteries',
          ],
          preparationTips: [
            'Rinse cans to remove food residue',
            'Crush cans to save space',
            'Clean aluminium foil before recycling',
            'Check locally for aerosol disposal rules',
          ],
          funFact:
              'Recycling aluminium uses only 5% of the energy needed to produce new aluminium!',
          recycleSymbol: '🥫',
        ),
        RecyclingCategory(
          id: 'general',
          name: 'General',
          icon: Icons.delete_outline,
          color: AppColors.generalColor,
          lightColor: AppColors.generalLight,
          description: 'Non-recyclable waste for landfill',
          whatGoesIn: [
            'Food-soiled packaging',
            'Nappies and sanitary products',
            'Broken crockery',
            'Used tissues and paper towels',
            'Non-recyclable plastics',
            'Polystyrene containers',
          ],
          whatStaysOut: [
            'Recyclable materials (use correct bin)',
            'Batteries (hazardous waste)',
            'Chemicals and paint',
            'Medical waste',
            'Electronic items',
          ],
          preparationTips: [
            'Always try to recycle before using general waste',
            'Reduce waste by choosing reusable products',
            'Compost food scraps where possible',
            'Check local council guidelines',
          ],
          funFact:
              'The average person generates 4.5 pounds of trash per day. Small changes make a big difference!',
          recycleSymbol: '🗑️',
        ),
        RecyclingCategory(
          id: 'ewaste',
          name: 'E-Waste',
          icon: Icons.devices_outlined,
          color: AppColors.eWasteColor,
          lightColor: AppColors.eWasteLight,
          description: 'Electronic devices and batteries',
          whatGoesIn: [
            'Phones and tablets',
            'Computers and laptops',
            'Batteries (all types)',
            'Cables and chargers',
            'Printers and scanners',
            'TVs and monitors',
          ],
          whatStaysOut: [
            'General recycling bins',
            'Regular landfill',
          ],
          preparationTips: [
            'Wipe personal data before recycling',
            'Take to designated e-waste collection points',
            'Check manufacturer take-back programs',
            'Never put batteries in regular bins',
          ],
          funFact:
              'E-waste is the fastest-growing waste stream in the world, but it contains valuable metals like gold and silver!',
          recycleSymbol: '💻',
        ),
        RecyclingCategory(
          id: 'organic',
          name: 'Organic',
          icon: Icons.eco_outlined,
          color: AppColors.organicColor,
          lightColor: AppColors.organicLight,
          description: 'Food and garden organic waste',
          whatGoesIn: [
            'Fruit and vegetable scraps',
            'Coffee grounds and tea bags',
            'Garden clippings',
            'Bread and grains',
            'Eggshells',
            'Leaves and grass',
          ],
          whatStaysOut: [
            'Meat, fish, and dairy (unless home-composting permits)',
            'Diseased plants',
            'Pet waste',
            'Oily or processed foods',
          ],
          preparationTips: [
            'Use a compost bin for food scraps',
            'Layer "green" and "brown" compost materials',
            'Keep organic bin from getting too wet',
            'Check local green bin collection schedule',
          ],
          funFact:
              'Composting food waste can reduce household landfill contributions by up to 30%!',
          recycleSymbol: '🍃',
        ),
      ];

  static Map<String, RecyclingCategory> get categoriesMap {
    return {for (var c in categories) c.id: c};
  }

  // Sample barcode product database
  static final List<Map<String, dynamic>> productDatabase = [
    {
      'barcode': '5000112637939',
      'name': 'Coca-Cola 500ml Bottle',
      'brand': 'Coca-Cola',
      'categoryId': 'plastic',
      'imageEmoji': '🥤',
      'notes': 'PET plastic bottle (type 1). Remove cap before recycling.',
    },
    {
      'barcode': '7622300489434',
      'name': 'Oreo Cookies Pack',
      'brand': 'Oreo',
      'categoryId': 'general',
      'imageEmoji': '🍪',
      'notes': 'Multi-layer packaging — not recyclable.',
    },
    {
      'barcode': '5010069230823',
      'name': 'Heinz Baked Beans',
      'brand': 'Heinz',
      'categoryId': 'metal',
      'imageEmoji': '🥫',
      'notes': 'Steel can. Rinse before recycling.',
    },
    {
      'barcode': '3017620422003',
      'name': 'Nutella 400g Jar',
      'brand': 'Ferrero',
      'categoryId': 'glass',
      'imageEmoji': '🫙',
      'notes': 'Glass jar. Rinse thoroughly.',
    },
    {
      'barcode': '5000168013218',
      'name': 'Cadbury Dairy Milk',
      'brand': 'Cadbury',
      'categoryId': 'general',
      'imageEmoji': '🍫',
      'notes': 'Foil and plastic wrapper — general waste.',
    },
    {
      'barcode': '5449000000996',
      'name': 'Coca-Cola Can 330ml',
      'brand': 'Coca-Cola',
      'categoryId': 'metal',
      'imageEmoji': '🥤',
      'notes': 'Aluminium can. Crush after use.',
    },
    {
      'barcode': '4006381333931',
      'name': 'NIVEA Body Lotion',
      'brand': 'NIVEA',
      'categoryId': 'plastic',
      'imageEmoji': '🧴',
      'notes': 'HDPE plastic bottle (type 2). Rinse and recycle.',
    },
    {
      'barcode': '5000120102348',
      'name': 'Fairy Washing Up Liquid',
      'brand': 'Fairy',
      'categoryId': 'plastic',
      'imageEmoji': '🫧',
      'notes': 'PET bottle. Empty and rinse before recycling.',
    },
    {
      'barcode': '8001120830012',
      'name': 'Barilla Pasta Box',
      'brand': 'Barilla',
      'categoryId': 'paper',
      'imageEmoji': '📦',
      'notes': 'Cardboard box. Flatten before recycling.',
    },
    {
      'barcode': '3228857000906',
      'name': 'Evian Water 1.5L',
      'brand': 'Evian',
      'categoryId': 'plastic',
      'imageEmoji': '💧',
      'notes': 'PET plastic bottle (type 1). Remove cap.',
    },
    {
      'barcode': '5010477374809',
      'name': 'HP Brown Sauce',
      'brand': 'HP',
      'categoryId': 'glass',
      'imageEmoji': '🍶',
      'notes': 'Glass bottle. Rinse before recycling.',
    },
    {
      'barcode': '8000500310427',
      'name': 'Ferrero Rocher Box',
      'brand': 'Ferrero',
      'categoryId': 'general',
      'imageEmoji': '🍬',
      'notes': 'Mixed materials — general waste.',
    },
    {
      'barcode': '5010337030006',
      'name': 'Tropicana Orange Juice',
      'brand': 'Tropicana',
      'categoryId': 'general',
      'imageEmoji': '🍊',
      'notes': 'Tetra Pak carton — check local facilities.',
    },
    {
      'barcode': '4005900380906',
      'name': 'Pringles Original',
      'brand': 'Pringles',
      'categoryId': 'general',
      'imageEmoji': '🥔',
      'notes': 'Composite tube — difficult to recycle. General waste.',
    },
    {
      'barcode': '7613035604957',
      'name': 'Nescafé Gold Coffee',
      'brand': 'Nescafé',
      'categoryId': 'glass',
      'imageEmoji': '☕',
      'notes': 'Glass jar. Remove lid (metal) separately.',
    },
    {
      'barcode': '5000112548167',
      'name': 'Sprite 2L Bottle',
      'brand': 'Sprite',
      'categoryId': 'plastic',
      'imageEmoji': '🥤',
      'notes': 'PET bottle (type 1). Recycle with caps removed.',
    },
    {
      'barcode': '5010044002560',
      'name': 'Anchor Butter',
      'brand': 'Anchor',
      'categoryId': 'paper',
      'imageEmoji': '🧈',
      'notes': 'Cardboard and foil packaging. Separate foil.',
    },
    {
      'barcode': '5000193001031',
      'name': 'Walkers Crisps',
      'brand': 'Walkers',
      'categoryId': 'general',
      'imageEmoji': '🥨',
      'notes': 'Metallised plastic film — not recyclable.',
    },
    {
      'barcode': '0012000001086',
      'name': 'Pepsi Cola Can',
      'brand': 'Pepsi',
      'categoryId': 'metal',
      'imageEmoji': '🥤',
      'notes': 'Aluminium can. Crush and recycle.',
    },
    {
      'barcode': '5010663213217',
      'name': 'Persil Washing Powder',
      'brand': 'Persil',
      'categoryId': 'paper',
      'imageEmoji': '📦',
      'notes': 'Cardboard box. Recyclable in paper bin.',
    },
  ];

  static final List<String> ecoTips = [
    '♻️ Rinse plastic bottles and containers before putting them in the recycling bin.',
    '🌳 Recycling one tonne of paper saves 17 trees and 7,000 gallons of water.',
    '💧 A dripping tap can waste up to 20 litres of water per day. Fix it!',
    '🥤 Aluminium cans can be back on the shelf as a new product in just 60 days.',
    '🛍️ Bring reusable bags when shopping to reduce single-use plastic waste.',
    '💡 Switching to LED bulbs uses 75% less energy than traditional incandescent bulbs.',
    '🍃 Composting food scraps can reduce your household landfill waste by up to 30%.',
    '🔋 Never put batteries in the general waste — take them to a collection point.',
    '📱 Old phones contain gold, silver, and copper — recycle your e-waste!',
    '🚿 Cutting your shower by 2 minutes saves around 15 litres of water.',
    '🌍 Glass can be recycled endlessly without losing quality.',
    '🧴 Empty your containers fully before recycling — even a small amount of product causes contamination.',
    '🥡 Greasy pizza boxes cannot be recycled — tear off and recycle the clean top half.',
    '☕ Coffee pods are hard to recycle — consider switching to a reusable cup or pod.',
    '🌿 Growing herbs at home reduces packaging waste from store-bought herbs.',
    '🎁 Wrapping paper with glitter or foil is not recyclable — opt for plain paper or fabric.',
    '🚗 Carpooling just twice a week can reduce your carbon footprint by up to 1,590 lbs of CO₂ per year.',
    '🧺 Washing clothes at 30°C rather than 60°C uses 60% less energy.',
    '🍎 Buying local and seasonal produce reduces food miles and supports local farmers.',
    '📦 Flatten cardboard boxes before putting them in the recycling bin to save space.',
    '🌊 Never pour cooking oil down the drain — it clogs pipes and harms waterways.',
    '🐝 Planting flowers like lavender and sunflowers helps support bee populations.',
    '🧴 Refill your cleaning product bottles instead of buying new ones to reduce plastic.',
    '📰 Old newspapers can be used as eco-friendly wrapping paper.',
    '🔌 Unplug chargers and electronics when not in use to save phantom energy.',
    '🍋 Use natural cleaning products like lemon juice and vinegar to reduce chemical waste.',
    '🛒 Buying in bulk reduces packaging waste per item.',
    '🌱 Start a window herb garden — even a small one makes a difference!',
    '👕 Donate old clothes instead of throwing them away — one person\'s trash is another\'s treasure.',
    '🏡 Insulating your home properly can reduce your heating bill by up to 25%.',
  ];
}
